# === Taps ===
tap "gromgit/fuse"
tap "heroku/brew"
tap "jstkdng/programs"
tap "laishulu/homebrew"
tap "homebrew-zathura/zathura", "https://github.com/homebrew-zathura/homebrew-zathura.git"

# === Core CLI ===
brew "mise"
brew "git"
brew "gh"
brew "ghq"
brew "tmux"
brew "bob"
brew "fzf"
brew "peco"
brew "ripgrep"
brew "zoxide"
brew "direnv"
brew "tree"
brew "watch"
brew "wget"
brew "yazi"
brew "zplug"
brew "bib-tool"
brew "lazygit"
brew "git-secrets"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "uv"
brew "ykman"

# === Build / System Libraries ===
brew "cmake"
brew "fontconfig"
brew "glib"
brew "libtiff"
brew "gdk-pixbuf"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "at-spi2-core"
brew "libavif"
brew "gobject-introspection"
brew "gtk+3"
brew "libffi"
brew "libfido2"
brew "libsixel"
brew "netpbm"

# === Media / Document Tools ===
brew "ffmpeg"
brew "ffmpegthumbnailer"
brew "imagemagick"
brew "ghostscript"
brew "graphviz"
brew "mupdf-tools"
brew "latexindent"

# === Database Servers ===
brew "mysql"
brew "mysql-client"
brew "redis"

# === Container / VM ===
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "qemu"
brew "lima-additional-guestagents"

# === Mobile Dev ===
brew "cocoapods"
brew "ios-deploy"

# === Other ===
brew "protobuf"
brew "opencv"
brew "unar"

# === External taps ===
brew "heroku/brew/heroku"
brew "jstkdng/programs/ueberzugpp"
brew "laishulu/homebrew/macism"
brew "homebrew-zathura/zathura/zathura"
brew "homebrew-zathura/zathura/zathura-pdf-poppler"

# === Fonts ===
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "hammerspoon"

# === Applications ===
cask "background-music"
cask "chatgpt"
cask "claude"
cask "claude-code"
cask "codex"
cask "craft"
cask "figma"
cask "google-chrome"
cask "intellij-idea"
cask "libreoffice"
cask "notion"
cask "podman-desktop"
cask "slack"
cask "wezterm"
