# Plugin-specific options
set -g @nord_tmux_show_status_content "0"
set -g @continuum-save-interval '10'
set -g @continuum-restore 'on'

# TPM plugin order matters.
# Keep tmux-continuum last so its autosave hook stays attached to status-right.
set -g @plugin 'tmux-plugins/tpm'
# tmux session plugins
#set -g @plugin 'catppuccin/tmux'
# set -g @plugin "nordtheme/tmux"
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'vimhack/tmux-moon-phase#main'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
