# Set status bar
set-option -g status-style bg=default
set -g status-left-length 140
set -g status-right-length 200
set -g status-left '#[fg=#{?client_prefix,colour233,white},bg=#{?client_prefix,colour45,default}]   #S   #[fg=#{?client_prefix,colour45,colour45},bg=default]   '
setw -g window-status-current-format '#[bg=default,fg=colour81]#I #W #[fg=colour81,bg=default,nobold,noitalics,nounderscore]☾ '
set -g status-right "#(~/.tmux/work_time_gauge/work_time_gauge.sh #{session_name} show) #{moon_phase_icon} #{moon_phase_text} #[bg=default, fg=colour45]󰜃 #[bg=default, fg=colour45]#{USER} #[bg=default, fg=colour45] #H"
